### ISSUE TITLE
Missing workspaces in overview bug when using dash to dock

### ISSUE THREAD

**Issue by n3thshan** [axxapy/gnome-ui-tune#29]
When using muter its pretty fine but when using dynamic buffering this issue persists, probably the reason as to why this bug is present in Ubuntu. When enabling search in settings the issue doesnt reoccur but it is not accepatable. I hope the developer fixes this issue as at the moment i have to rely on this extension as well as just perfection extension to get rid of search and not have this bug. Thank you!

**Comment by n3thshan** [comment]
> When using muter its pretty fine but when using dynamic buffering this issue persists, probably the reason as to why this bug is present in Ubuntu. When enabling search in settings the issue doesnt reoccur but it is not accepatable. I hope the developer fixes this issue as at the moment i have to rely on this extension as well as just perfection extension to get rid of search and not have this bug. Thank you!

So i found the culprit!. It wasnt mutter, infact it is dash to dock extension! Please look into this dev!

**Comment by soumyaDghosh** [comment]
Same here, It was almost a very big reason for me to leave ubuntu. But now, after a lot of tests, I found out that when I enable the search option again, the workspaces can be seen again

**Comment by axxapy** [comment]
fixed/hacked in #17

**Comment by soumyaDghosh** [comment]
This is not yet fixed for the ubuntu-dock. I have to disable the 'hide search feature' to use it properly.

**Comment by axxapy** [comment]
> This is not yet fixed for the ubuntu-dock. I have to disable the 'hide search feature' to use it properly.

Just tested with freshly downloaded 22.04 in virtual machine. No issues.
You'd have to be much more specific if you want it to be addressed or, better, investigate it yourself. Line that hides search can not have bugs by its nature: https://github.com/axxapy/gnome-ui-tune/blob/master/src/modHideSearchInput.js#L15 .

**Comment by soumyaDghosh** [comment]
> > This is not yet fixed for the ubuntu-dock. I have to disable the 'hide search feature' to use it properly.
> 
> Just tested with freshly downloaded 22.04 in virtual machine. No issues. You'd have to be much more specific if you want it to be addressed or, better, investigate it yourself. Line that hides search can not have bugs by its nature: https://github.com/axxapy/gnome-ui-tune/blob/master/src/modHideSearchInput.js#L15 .

Same, you can see the screenshot below, that's also a freshly installed vm of Ubuntu 22.04 LTS
![Screenshot from 2022-09-25 12-35-11](https://user-images.githubusercontent.com/72045785/192132417-2a8e3174-5ab1-43bb-a265-cdecfb5dca9f.png)
